module Evergreen.Migrate.V138 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V138.Api.Logging
import Evergreen.V138.Api.User
import Evergreen.V138.Api.YoutubeModel
import Evergreen.V138.Types
import Evergreen.V94.Api.Logging
import Evergreen.V94.Api.User
import Evergreen.V94.Api.YoutubeModel
import Evergreen.V94.Types
import Lamdera.Migrations exposing (..)
import List
import Time


frontendModel : Evergreen.V94.Types.FrontendModel -> ModelMigration Evergreen.V138.Types.FrontendModel Evergreen.V138.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V94.Types.BackendModel -> ModelMigration Evergreen.V138.Types.BackendModel Evergreen.V138.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V94.Types.FrontendMsg -> MsgMigration Evergreen.V138.Types.FrontendMsg Evergreen.V138.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V94.Types.ToBackend -> MsgMigration Evergreen.V138.Types.ToBackend Evergreen.V138.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V94.Types.BackendMsg -> MsgMigration Evergreen.V138.Types.BackendMsg Evergreen.V138.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V94.Types.ToFrontend -> MsgMigration Evergreen.V138.Types.ToFrontend Evergreen.V138.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_BackendModel : Evergreen.V94.Types.BackendModel -> Evergreen.V138.Types.BackendModel
migrate_Types_BackendModel old =
    { users = old.users |> Dict.map (\k -> migrate_Api_User_UserFull)
    , authenticatedSessions = old.authenticatedSessions
    , incrementedInt = old.incrementedInt
    , logs = old.logs |> List.map migrate_Api_Logging_LogEntry
    , clientCredentials = old.clientCredentials
    , channels = old.channels
    , channelAssociations = old.channelAssociations
    , playlists = old.playlists
    , competitors = old.competitors
    , schedules = old.schedules
    , videos = old.videos |> Dict.map (\k -> migrate_Api_YoutubeModel_Video)
    , videoStatisticsAtTime = old.videoStatisticsAtTime
    , liveVideoDetails = old.liveVideoDetails
    , currentViewers = old.currentViewers
    , channelHandleMap = old.channelHandleMap
    , apiCallCount = old.apiCallCount
    , time = old.time
    , greetingStr = "Hello julle"
    }


migrate_Api_Logging_LogEntry : Evergreen.V94.Api.Logging.LogEntry -> Evergreen.V138.Api.Logging.LogEntry
migrate_Api_Logging_LogEntry old =
    { message = old.message
    , timestamp = old.timestamp
    , logLevel = old.logLevel |> migrate_Api_Logging_LogLevel
    }


migrate_Api_Logging_LogLevel : Evergreen.V94.Api.Logging.LogLevel -> Evergreen.V138.Api.Logging.LogLevel
migrate_Api_Logging_LogLevel old =
    case old of
        Evergreen.V94.Api.Logging.Error ->
            Evergreen.V138.Api.Logging.Error

        Evergreen.V94.Api.Logging.Info ->
            Evergreen.V138.Api.Logging.Info

        Evergreen.V94.Api.Logging.Alert ->
            Evergreen.V138.Api.Logging.Alert


migrate_Api_User_Role : Evergreen.V94.Api.User.Role -> Evergreen.V138.Api.User.Role
migrate_Api_User_Role old =
    case old of
        Evergreen.V94.Api.User.Basic ->
            Evergreen.V138.Api.User.Basic

        Evergreen.V94.Api.User.Editor ->
            Evergreen.V138.Api.User.Editor

        Evergreen.V94.Api.User.Admin ->
            Evergreen.V138.Api.User.Admin


migrate_Api_User_UserFull : Evergreen.V94.Api.User.UserFull -> Evergreen.V138.Api.User.UserFull
migrate_Api_User_UserFull old =
    { email = old.email
    , role = old.role |> migrate_Api_User_Role
    , passwordHash = old.passwordHash
    , salt = old.salt
    }


migrate_Api_YoutubeModel_LiveStatus : Evergreen.V94.Api.YoutubeModel.LiveStatus -> Evergreen.V138.Api.YoutubeModel.LiveStatus
migrate_Api_YoutubeModel_LiveStatus old =
    case old of
        Evergreen.V94.Api.YoutubeModel.Unknown ->
            Evergreen.V138.Api.YoutubeModel.Unknown

        Evergreen.V94.Api.YoutubeModel.Uploaded ->
            Evergreen.V138.Api.YoutubeModel.Uploaded

        Evergreen.V94.Api.YoutubeModel.Scheduled p0 ->
            Evergreen.V138.Api.YoutubeModel.Scheduled p0

        Evergreen.V94.Api.YoutubeModel.Expired ->
            Evergreen.V138.Api.YoutubeModel.Expired

        Evergreen.V94.Api.YoutubeModel.Old ->
            Evergreen.V138.Api.YoutubeModel.Old

        Evergreen.V94.Api.YoutubeModel.Live ->
            Evergreen.V138.Api.YoutubeModel.Live

        Evergreen.V94.Api.YoutubeModel.Ended p0 ->
            Evergreen.V138.Api.YoutubeModel.Ended p0

        Evergreen.V94.Api.YoutubeModel.Impossibru ->
            Evergreen.V138.Api.YoutubeModel.Impossibru


migrate_Api_YoutubeModel_Video : Evergreen.V94.Api.YoutubeModel.Video -> Evergreen.V138.Api.YoutubeModel.Video
migrate_Api_YoutubeModel_Video old =
    { id = old.id
    , title = old.title
    , description = old.description
    , videoOwnerChannelId = old.videoOwnerChannelId
    , videoOwnerChannelTitle = old.videoOwnerChannelTitle
    , playlistId = old.playlistId
    , thumbnailUrl = old.thumbnailUrl
    , publishedAt = old.publishedAt
    , liveChatId = old.liveChatId
    , liveStatus = old.liveStatus |> migrate_Api_YoutubeModel_LiveStatus
    , statsOnConclusion = old.statsOnConclusion
    , statsAfter24Hours = old.statsAfter24Hours
    , reportAfter24Hours = old.reportAfter24Hours
    , chatMsgCount = old.chatMsgCount
    , ctr = old.ctr
    , liveViews = old.liveViews
    }
