module Evergreen.Migrate.V36 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V35.Api.Logging
import Evergreen.V35.Api.User
import Evergreen.V35.Api.YoutubeModel
import Evergreen.V35.Gen.Model
import Evergreen.V35.Gen.Pages
import Evergreen.V35.Gen.Params.Channel.Id_
import Evergreen.V35.Gen.Params.Ga.Email_
import Evergreen.V35.Gen.Params.Playlist.Id_
import Evergreen.V35.Pages.Admin
import Evergreen.V35.Pages.Channel.Id_
import Evergreen.V35.Pages.End
import Evergreen.V35.Pages.Example
import Evergreen.V35.Pages.Ga.Email_
import Evergreen.V35.Pages.Home_
import Evergreen.V35.Pages.Log
import Evergreen.V35.Pages.Login
import Evergreen.V35.Pages.Playlist.Id_
import Evergreen.V35.Pages.Register
import Evergreen.V35.Shared
import Evergreen.V35.Types
import Evergreen.V36.Api.Logging
import Evergreen.V36.Api.User
import Evergreen.V36.Api.YoutubeModel
import Evergreen.V36.Gen.Model
import Evergreen.V36.Gen.Pages
import Evergreen.V36.Gen.Params.Channel.Id_
import Evergreen.V36.Gen.Params.Ga.Email_
import Evergreen.V36.Gen.Params.Playlist.Id_
import Evergreen.V36.Pages.Admin
import Evergreen.V36.Pages.Channel.Id_
import Evergreen.V36.Pages.End
import Evergreen.V36.Pages.Example
import Evergreen.V36.Pages.Ga.Email_
import Evergreen.V36.Pages.Home_
import Evergreen.V36.Pages.Log
import Evergreen.V36.Pages.Login
import Evergreen.V36.Pages.Playlist.Id_
import Evergreen.V36.Pages.Register
import Evergreen.V36.Shared
import Evergreen.V36.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V35.Types.FrontendModel -> ModelMigration Evergreen.V36.Types.FrontendModel Evergreen.V36.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V35.Types.BackendModel -> ModelMigration Evergreen.V36.Types.BackendModel Evergreen.V36.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V35.Types.FrontendMsg -> MsgMigration Evergreen.V36.Types.FrontendMsg Evergreen.V36.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V35.Types.ToBackend -> MsgMigration Evergreen.V36.Types.ToBackend Evergreen.V36.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V35.Types.BackendMsg -> MsgMigration Evergreen.V36.Types.BackendMsg Evergreen.V36.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V35.Types.ToFrontend -> MsgMigration Evergreen.V36.Types.ToFrontend Evergreen.V36.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V35.Types.FrontendModel -> Evergreen.V36.Types.FrontendModel
migrate_Types_FrontendModel old =
    { url = old.url
    , key = old.key
    , shared = old.shared |> migrate_Shared_Model
    , page = old.page |> migrate_Gen_Pages_Model
    }


migrate_Api_Logging_LogEntry : Evergreen.V35.Api.Logging.LogEntry -> Evergreen.V36.Api.Logging.LogEntry
migrate_Api_Logging_LogEntry old =
    { message = old.message
    , timestamp = old.timestamp
    , logLevel = old.logLevel |> migrate_Api_Logging_LogLevel
    }


migrate_Api_Logging_LogLevel : Evergreen.V35.Api.Logging.LogLevel -> Evergreen.V36.Api.Logging.LogLevel
migrate_Api_Logging_LogLevel old =
    case old of
        Evergreen.V35.Api.Logging.Error ->
            Evergreen.V36.Api.Logging.Error

        Evergreen.V35.Api.Logging.Info ->
            Evergreen.V36.Api.Logging.Info

        Evergreen.V35.Api.Logging.Alert ->
            Evergreen.V36.Api.Logging.Alert


migrate_Api_User_Role : Evergreen.V35.Api.User.Role -> Evergreen.V36.Api.User.Role
migrate_Api_User_Role old =
    case old of
        Evergreen.V35.Api.User.Basic ->
            Evergreen.V36.Api.User.Basic

        Evergreen.V35.Api.User.Editor ->
            Evergreen.V36.Api.User.Editor

        Evergreen.V35.Api.User.Admin ->
            Evergreen.V36.Api.User.Admin


migrate_Api_User_User : Evergreen.V35.Api.User.User -> Evergreen.V36.Api.User.User
migrate_Api_User_User old =
    { email = old.email
    , role = old.role |> migrate_Api_User_Role
    }


migrate_Api_YoutubeModel_LiveStatus : Evergreen.V35.Api.YoutubeModel.LiveStatus -> Evergreen.V36.Api.YoutubeModel.LiveStatus
migrate_Api_YoutubeModel_LiveStatus old =
    case old of
        Evergreen.V35.Api.YoutubeModel.Unknown ->
            Evergreen.V36.Api.YoutubeModel.Unknown

        Evergreen.V35.Api.YoutubeModel.Uploaded ->
            Evergreen.V36.Api.YoutubeModel.Uploaded

        Evergreen.V35.Api.YoutubeModel.Scheduled p0 ->
            Evergreen.V36.Api.YoutubeModel.Scheduled p0

        Evergreen.V35.Api.YoutubeModel.Expired ->
            Evergreen.V36.Api.YoutubeModel.Expired

        Evergreen.V35.Api.YoutubeModel.Old ->
            Evergreen.V36.Api.YoutubeModel.Old

        Evergreen.V35.Api.YoutubeModel.Live ->
            Evergreen.V36.Api.YoutubeModel.Live

        Evergreen.V35.Api.YoutubeModel.Ended p0 ->
            Evergreen.V36.Api.YoutubeModel.Ended p0

        Evergreen.V35.Api.YoutubeModel.Impossibru ->
            Evergreen.V36.Api.YoutubeModel.Impossibru


migrate_Api_YoutubeModel_Video : Evergreen.V35.Api.YoutubeModel.Video -> Evergreen.V36.Api.YoutubeModel.Video
migrate_Api_YoutubeModel_Video old =
    { id = old.id
    , title = old.title
    , description = old.description
    , videoOwnerChannelId = old.videoOwnerChannelId
    , videoOwnerChannelTitle = old.videoOwnerChannelTitle
    , playlistId = old.playlistId
    , thumbnailUrl = old.thumbnailUrl
    , publishedAt = old.publishedAt
    , liveChatId = old.liveChatId
    , liveStatus = old.liveStatus |> migrate_Api_YoutubeModel_LiveStatus
    , statsOnConclusion = old.statsOnConclusion
    , statsAfter24Hours = old.statsAfter24Hours
    , reportAfter24Hours = old.reportAfter24Hours
    , chatMsgCount = old.chatMsgCount
    }


migrate_Gen_Model_Model : Evergreen.V35.Gen.Model.Model -> Evergreen.V36.Gen.Model.Model
migrate_Gen_Model_Model old =
    case old of
        Evergreen.V35.Gen.Model.Redirecting_ ->
            Evergreen.V36.Gen.Model.Redirecting_

        Evergreen.V35.Gen.Model.Admin p0 p1 ->
            Evergreen.V36.Gen.Model.Admin p0 (p1 |> migrate_Pages_Admin_Model)

        Evergreen.V35.Gen.Model.End p0 p1 ->
            Evergreen.V36.Gen.Model.End p0 (p1 |> migrate_Pages_End_Model)

        Evergreen.V35.Gen.Model.Example p0 p1 ->
            Evergreen.V36.Gen.Model.Example p0 (p1 |> migrate_Pages_Example_Model)

        Evergreen.V35.Gen.Model.Home_ p0 p1 ->
            Evergreen.V36.Gen.Model.Home_ p0 (p1 |> migrate_Pages_Home__Model)

        Evergreen.V35.Gen.Model.Log p0 p1 ->
            Evergreen.V36.Gen.Model.Log p0 (p1 |> migrate_Pages_Log_Model)

        Evergreen.V35.Gen.Model.Login p0 p1 ->
            Evergreen.V36.Gen.Model.Login p0 (p1 |> migrate_Pages_Login_Model)

        Evergreen.V35.Gen.Model.NotFound p0 ->
            Evergreen.V36.Gen.Model.NotFound p0

        Evergreen.V35.Gen.Model.Register p0 p1 ->
            Evergreen.V36.Gen.Model.Register p0 (p1 |> migrate_Pages_Register_Model)

        Evergreen.V35.Gen.Model.Channel__Id_ p0 p1 ->
            Evergreen.V36.Gen.Model.Channel__Id_ (p0 |> migrate_Gen_Params_Channel_Id__Params)
                (p1 |> migrate_Pages_Channel_Id__Model)

        Evergreen.V35.Gen.Model.Ga__Email_ p0 p1 ->
            Evergreen.V36.Gen.Model.Ga__Email_ (p0 |> migrate_Gen_Params_Ga_Email__Params)
                (p1 |> migrate_Pages_Ga_Email__Model)

        Evergreen.V35.Gen.Model.Playlist__Id_ p0 p1 ->
            Evergreen.V36.Gen.Model.Playlist__Id_ (p0 |> migrate_Gen_Params_Playlist_Id__Params)
                (p1 |> migrate_Pages_Playlist_Id__Model)


migrate_Gen_Pages_Model : Evergreen.V35.Gen.Pages.Model -> Evergreen.V36.Gen.Pages.Model
migrate_Gen_Pages_Model old =
    old |> migrate_Gen_Model_Model


migrate_Gen_Params_Channel_Id__Params : Evergreen.V35.Gen.Params.Channel.Id_.Params -> Evergreen.V36.Gen.Params.Channel.Id_.Params
migrate_Gen_Params_Channel_Id__Params old =
    old


migrate_Gen_Params_Ga_Email__Params : Evergreen.V35.Gen.Params.Ga.Email_.Params -> Evergreen.V36.Gen.Params.Ga.Email_.Params
migrate_Gen_Params_Ga_Email__Params old =
    old


migrate_Gen_Params_Playlist_Id__Params : Evergreen.V35.Gen.Params.Playlist.Id_.Params -> Evergreen.V36.Gen.Params.Playlist.Id_.Params
migrate_Gen_Params_Playlist_Id__Params old =
    old


migrate_Pages_Admin_Model : Evergreen.V35.Pages.Admin.Model -> Evergreen.V36.Pages.Admin.Model
migrate_Pages_Admin_Model old =
    old


migrate_Pages_Channel_Id__Model : Evergreen.V35.Pages.Channel.Id_.Model -> Evergreen.V36.Pages.Channel.Id_.Model
migrate_Pages_Channel_Id__Model old =
    { channelId = old.channelId
    , channel = old.channel
    , playlists = old.playlists
    , latestVideos = old.latestVideos
    , schedules = old.schedules
    , tmpCompetitors = Dict.empty
    }


migrate_Pages_End_Model : Evergreen.V35.Pages.End.Model -> Evergreen.V36.Pages.End.Model
migrate_Pages_End_Model old =
    old


migrate_Pages_Example_Model : Evergreen.V35.Pages.Example.Model -> Evergreen.V36.Pages.Example.Model
migrate_Pages_Example_Model old =
    old


migrate_Pages_Ga_Email__Model : Evergreen.V35.Pages.Ga.Email_.Model -> Evergreen.V36.Pages.Ga.Email_.Model
migrate_Pages_Ga_Email__Model old =
    old


migrate_Pages_Home__Model : Evergreen.V35.Pages.Home_.Model -> Evergreen.V36.Pages.Home_.Model
migrate_Pages_Home__Model old =
    old


migrate_Pages_Log_Model : Evergreen.V35.Pages.Log.Model -> Evergreen.V36.Pages.Log.Model
migrate_Pages_Log_Model old =
    { logs = old.logs |> List.map migrate_Api_Logging_LogEntry
    , logIndex = old.logIndex
    }


migrate_Pages_Login_Model : Evergreen.V35.Pages.Login.Model -> Evergreen.V36.Pages.Login.Model
migrate_Pages_Login_Model old =
    old


migrate_Pages_Playlist_Id__Model : Evergreen.V35.Pages.Playlist.Id_.Model -> Evergreen.V36.Pages.Playlist.Id_.Model
migrate_Pages_Playlist_Id__Model old =
    { playlistId = old.playlistId
    , playlistTitle = old.playlistTitle
    , videos = old.videos |> Dict.map (\k -> migrate_Api_YoutubeModel_Video)
    , liveVideoDetails = old.liveVideoDetails
    , currentViewers = old.currentViewers
    , videoChannels = old.videoChannels
    , playlists = old.playlists
    , videoStats = old.videoStats
    }


migrate_Pages_Register_Model : Evergreen.V35.Pages.Register.Model -> Evergreen.V36.Pages.Register.Model
migrate_Pages_Register_Model old =
    old


migrate_Shared_Model : Evergreen.V35.Shared.Model -> Evergreen.V36.Shared.Model
migrate_Shared_Model old =
    { viewWidth = old.viewWidth
    , user = old.user |> Maybe.map migrate_Api_User_User
    , toastMessage = old.toastMessage
    }
