module Evergreen.Migrate.V50 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V48.Api.Logging
import Evergreen.V48.Api.User
import Evergreen.V48.Json.Auto.PlaylistItems
import Evergreen.V48.Types
import Evergreen.V50.Api.Logging
import Evergreen.V50.Api.User
import Evergreen.V50.Json.Auto.PlaylistItems
import Evergreen.V50.Types
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V48.Types.FrontendModel -> ModelMigration Evergreen.V50.Types.FrontendModel Evergreen.V50.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V48.Types.BackendModel -> ModelMigration Evergreen.V50.Types.BackendModel Evergreen.V50.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V48.Types.FrontendMsg -> MsgMigration Evergreen.V50.Types.FrontendMsg Evergreen.V50.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V48.Types.ToBackend -> MsgMigration Evergreen.V50.Types.ToBackend Evergreen.V50.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V48.Types.BackendMsg -> MsgMigration Evergreen.V50.Types.BackendMsg Evergreen.V50.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V48.Types.ToFrontend -> MsgMigration Evergreen.V50.Types.ToFrontend Evergreen.V50.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Api_Logging_LogLevel : Evergreen.V48.Api.Logging.LogLevel -> Evergreen.V50.Api.Logging.LogLevel
migrate_Api_Logging_LogLevel old =
    case old of
        Evergreen.V48.Api.Logging.Error ->
            Evergreen.V50.Api.Logging.Error

        Evergreen.V48.Api.Logging.Info ->
            Evergreen.V50.Api.Logging.Info

        Evergreen.V48.Api.Logging.Alert ->
            Evergreen.V50.Api.Logging.Alert


migrate_Api_User_Role : Evergreen.V48.Api.User.Role -> Evergreen.V50.Api.User.Role
migrate_Api_User_Role old =
    case old of
        Evergreen.V48.Api.User.Basic ->
            Evergreen.V50.Api.User.Basic

        Evergreen.V48.Api.User.Editor ->
            Evergreen.V50.Api.User.Editor

        Evergreen.V48.Api.User.Admin ->
            Evergreen.V50.Api.User.Admin


migrate_Api_User_User : Evergreen.V48.Api.User.User -> Evergreen.V50.Api.User.User
migrate_Api_User_User old =
    { email = old.email
    , role = old.role |> migrate_Api_User_Role
    }


migrate_Json_Auto_PlaylistItems_Root : Evergreen.V48.Json.Auto.PlaylistItems.Root -> Evergreen.V50.Json.Auto.PlaylistItems.Root
migrate_Json_Auto_PlaylistItems_Root old =
    { etag = old.etag
    , items = old.items |> List.map migrate_Json_Auto_PlaylistItems_RootItemsObject
    , kind = old.kind
    , nextPageToken = old.nextPageToken
    , pageInfo = old.pageInfo |> migrate_Json_Auto_PlaylistItems_RootPageInfo
    }


migrate_Json_Auto_PlaylistItems_RootItemsObject : Evergreen.V48.Json.Auto.PlaylistItems.RootItemsObject -> Evergreen.V50.Json.Auto.PlaylistItems.RootItemsObject
migrate_Json_Auto_PlaylistItems_RootItemsObject old =
    { etag = old.etag
    , id = old.id
    , kind = old.kind
    , snippet = old.snippet |> migrate_Json_Auto_PlaylistItems_RootItemsObjectSnippet
    }


migrate_Json_Auto_PlaylistItems_RootItemsObjectSnippet : Evergreen.V48.Json.Auto.PlaylistItems.RootItemsObjectSnippet -> Evergreen.V50.Json.Auto.PlaylistItems.RootItemsObjectSnippet
migrate_Json_Auto_PlaylistItems_RootItemsObjectSnippet old =
    { channelId = old.channelId
    , channelTitle = old.channelTitle
    , description = old.description
    , playlistId = old.playlistId
    , position = old.position
    , publishedAt = old.publishedAt
    , resourceId = old.resourceId |> migrate_Json_Auto_PlaylistItems_RootItemsObjectSnippetResourceId
    , thumbnails = old.thumbnails
    , title = old.title
    , videoOwnerChannelId = old.videoOwnerChannelId |> Just
    , videoOwnerChannelTitle = old.videoOwnerChannelTitle |> Just
    }


migrate_Json_Auto_PlaylistItems_RootItemsObjectSnippetResourceId : Evergreen.V48.Json.Auto.PlaylistItems.RootItemsObjectSnippetResourceId -> Evergreen.V50.Json.Auto.PlaylistItems.RootItemsObjectSnippetResourceId
migrate_Json_Auto_PlaylistItems_RootItemsObjectSnippetResourceId old =
    old


migrate_Json_Auto_PlaylistItems_RootPageInfo : Evergreen.V48.Json.Auto.PlaylistItems.RootPageInfo -> Evergreen.V50.Json.Auto.PlaylistItems.RootPageInfo
migrate_Json_Auto_PlaylistItems_RootPageInfo old =
    old


migrate_Types_BackendMsg : Evergreen.V48.Types.BackendMsg -> Evergreen.V50.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V48.Types.OnConnect p0 p1 ->
            Evergreen.V50.Types.OnConnect p0 p1

        Evergreen.V48.Types.AuthenticateSession p0 p1 p2 p3 ->
            Evergreen.V50.Types.AuthenticateSession p0 p1 (p2 |> migrate_Api_User_User) p3

        Evergreen.V48.Types.VerifySession p0 p1 p2 ->
            Evergreen.V50.Types.VerifySession p0 p1 p2

        Evergreen.V48.Types.RegisterUser p0 p1 p2 p3 ->
            Evergreen.V50.Types.RegisterUser p0 p1 p2 p3

        Evergreen.V48.Types.Log_ p0 p1 p2 ->
            Evergreen.V50.Types.Log_ p0 (p1 |> migrate_Api_Logging_LogLevel) p2

        Evergreen.V48.Types.GotFreshAccessTokenWithTime p0 p1 p2 ->
            Evergreen.V50.Types.GotFreshAccessTokenWithTime p0 p1 p2

        Evergreen.V48.Types.Batch_RefreshAccessTokens p0 ->
            Evergreen.V50.Types.Batch_RefreshAccessTokens p0

        Evergreen.V48.Types.Batch_RefreshAllChannels p0 ->
            Evergreen.V50.Types.Batch_RefreshAllChannels p0

        Evergreen.V48.Types.Batch_RefreshAllPlaylists p0 ->
            Evergreen.V50.Types.Batch_RefreshAllPlaylists p0

        Evergreen.V48.Types.Batch_RefreshAllVideosFromPlaylists p0 ->
            Evergreen.V50.Types.Batch_RefreshAllVideosFromPlaylists p0

        Evergreen.V48.Types.Batch_GetLiveVideoStreamData p0 ->
            Evergreen.V50.Types.Batch_GetLiveVideoStreamData p0

        Evergreen.V48.Types.Batch_GetChatMessages p0 ->
            Evergreen.V50.Types.Batch_GetChatMessages p0

        Evergreen.V48.Types.Batch_GetVideoStats p0 ->
            Evergreen.V50.Types.Batch_GetVideoStats p0

        Evergreen.V48.Types.Batch_GetVideoDailyReports p0 ->
            Evergreen.V50.Types.Batch_GetVideoDailyReports p0

        Evergreen.V48.Types.Batch_GetVideoStatisticsAtTime p0 ->
            Evergreen.V50.Types.Batch_GetVideoStatisticsAtTime p0

        Evergreen.V48.Types.Batch_GetCompetitorChannelIds p0 ->
            Evergreen.V50.Types.Batch_GetCompetitorChannelIds p0

        Evergreen.V48.Types.Batch_GetCompetitorVideos p0 ->
            Evergreen.V50.Types.Batch_GetCompetitorVideos p0

        Evergreen.V48.Types.GetChannelId p0 ->
            Evergreen.V50.Types.GetChannelId p0

        Evergreen.V48.Types.GetAccessToken p0 p1 ->
            Evergreen.V50.Types.GetAccessToken p0 p1

        Evergreen.V48.Types.GotAccessToken p0 p1 p2 ->
            Evergreen.V50.Types.GotAccessToken p0 p1 p2

        Evergreen.V48.Types.GetChannelsByCredential p0 ->
            Evergreen.V50.Types.GetChannelsByCredential p0

        Evergreen.V48.Types.GotChannels p0 p1 ->
            Evergreen.V50.Types.GotChannels p0 p1

        Evergreen.V48.Types.GetPlaylistsByChannel p0 ->
            Evergreen.V50.Types.GetPlaylistsByChannel p0

        Evergreen.V48.Types.GotPlaylists p0 p1 ->
            Evergreen.V50.Types.GotPlaylists p0 p1

        Evergreen.V48.Types.GetVideosByPlaylist p0 p1 ->
            Evergreen.V50.Types.GetVideosByPlaylist p0 p1

        Evergreen.V48.Types.GotVideosFromPlaylist p0 p1 ->
            Evergreen.V50.Types.GotVideosFromPlaylist p0
                (p1 |> Result.map migrate_Json_Auto_PlaylistItems_Root)

        Evergreen.V48.Types.GotLiveVideoStreamData p0 p1 p2 ->
            Evergreen.V50.Types.GotLiveVideoStreamData p0 p1 p2

        Evergreen.V48.Types.GotVideoStatsOnConclusion p0 p1 p2 ->
            Evergreen.V50.Types.GotVideoStatsOnConclusion p0 p1 p2

        Evergreen.V48.Types.GotVideoStatsAfter24Hrs p0 p1 p2 ->
            Evergreen.V50.Types.GotVideoStatsAfter24Hrs p0 p1 p2

        Evergreen.V48.Types.GotVideoStatsOnTheHour p0 p1 p2 ->
            Evergreen.V50.Types.GotVideoStatsOnTheHour p0 p1 p2

        Evergreen.V48.Types.GotChatMessages p0 p1 ->
            Evergreen.V50.Types.GotChatMessages p0 p1

        Evergreen.V48.Types.GotVideoDailyReport p0 p1 ->
            Evergreen.V50.Types.GotVideoDailyReport p0 p1

        Evergreen.V48.Types.GotChannelId p0 p1 ->
            Evergreen.V50.Types.GotChannelId p0 p1

        Evergreen.V48.Types.GotCompetitorVideos p0 p1 ->
            Evergreen.V50.Types.GotCompetitorVideos p0 p1

        Evergreen.V48.Types.NoOpBackendMsg ->
            Evergreen.V50.Types.NoOpBackendMsg
