module Evergreen.Migrate.V71 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V66.Api.Logging
import Evergreen.V66.Api.User
import Evergreen.V66.Api.YoutubeModel
import Evergreen.V66.Types
import Evergreen.V71.Api.Logging
import Evergreen.V71.Api.User
import Evergreen.V71.Api.YoutubeModel
import Evergreen.V71.Types
import Lamdera.Migrations exposing (..)
import List
import Time


frontendModel : Evergreen.V66.Types.FrontendModel -> ModelMigration Evergreen.V71.Types.FrontendModel Evergreen.V71.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V66.Types.BackendModel -> ModelMigration Evergreen.V71.Types.BackendModel Evergreen.V71.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V66.Types.FrontendMsg -> MsgMigration Evergreen.V71.Types.FrontendMsg Evergreen.V71.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V66.Types.ToBackend -> MsgMigration Evergreen.V71.Types.ToBackend Evergreen.V71.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V66.Types.BackendMsg -> MsgMigration Evergreen.V71.Types.BackendMsg Evergreen.V71.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V66.Types.ToFrontend -> MsgMigration Evergreen.V71.Types.ToFrontend Evergreen.V71.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_BackendModel : Evergreen.V66.Types.BackendModel -> Evergreen.V71.Types.BackendModel
migrate_Types_BackendModel old =
    { users = old.users |> Dict.map (\k -> migrate_Api_User_UserFull)
    , authenticatedSessions = old.authenticatedSessions
    , incrementedInt = old.incrementedInt
    , logs = old.logs |> List.map migrate_Api_Logging_LogEntry
    , clientCredentials = old.clientCredentials
    , channels = old.channels
    , channelAssociations = old.channelAssociations
    , playlists = old.playlists
    , competitors = old.competitors
    , schedules = old.schedules
    , videos = old.videos |> Dict.map (\k -> migrate_Api_YoutubeModel_Video)
    , videoStatisticsAtTime = old.videoStatisticsAtTime
    , liveVideoDetails = old.liveVideoDetails
    , currentViewers = old.currentViewers
    , channelHandleMap = old.channelHandleMap
    , apiCallCount = old.apiCallCount
    , time = Time.millisToPosix 0
    }


migrate_Api_Logging_LogEntry : Evergreen.V66.Api.Logging.LogEntry -> Evergreen.V71.Api.Logging.LogEntry
migrate_Api_Logging_LogEntry old =
    { message = old.message
    , timestamp = old.timestamp
    , logLevel = old.logLevel |> migrate_Api_Logging_LogLevel
    }


migrate_Api_Logging_LogLevel : Evergreen.V66.Api.Logging.LogLevel -> Evergreen.V71.Api.Logging.LogLevel
migrate_Api_Logging_LogLevel old =
    case old of
        Evergreen.V66.Api.Logging.Error ->
            Evergreen.V71.Api.Logging.Error

        Evergreen.V66.Api.Logging.Info ->
            Evergreen.V71.Api.Logging.Info

        Evergreen.V66.Api.Logging.Alert ->
            Evergreen.V71.Api.Logging.Alert


migrate_Api_User_Role : Evergreen.V66.Api.User.Role -> Evergreen.V71.Api.User.Role
migrate_Api_User_Role old =
    case old of
        Evergreen.V66.Api.User.Basic ->
            Evergreen.V71.Api.User.Basic

        Evergreen.V66.Api.User.Editor ->
            Evergreen.V71.Api.User.Editor

        Evergreen.V66.Api.User.Admin ->
            Evergreen.V71.Api.User.Admin


migrate_Api_User_User : Evergreen.V66.Api.User.User -> Evergreen.V71.Api.User.User
migrate_Api_User_User old =
    { email = old.email
    , role = old.role |> migrate_Api_User_Role
    }


migrate_Api_User_UserFull : Evergreen.V66.Api.User.UserFull -> Evergreen.V71.Api.User.UserFull
migrate_Api_User_UserFull old =
    { email = old.email
    , role = old.role |> migrate_Api_User_Role
    , passwordHash = old.passwordHash
    , salt = old.salt
    }


migrate_Api_YoutubeModel_LiveStatus : Evergreen.V66.Api.YoutubeModel.LiveStatus -> Evergreen.V71.Api.YoutubeModel.LiveStatus
migrate_Api_YoutubeModel_LiveStatus old =
    case old of
        Evergreen.V66.Api.YoutubeModel.Unknown ->
            Evergreen.V71.Api.YoutubeModel.Unknown

        Evergreen.V66.Api.YoutubeModel.Uploaded ->
            Evergreen.V71.Api.YoutubeModel.Uploaded

        Evergreen.V66.Api.YoutubeModel.Scheduled p0 ->
            Evergreen.V71.Api.YoutubeModel.Scheduled p0

        Evergreen.V66.Api.YoutubeModel.Expired ->
            Evergreen.V71.Api.YoutubeModel.Expired

        Evergreen.V66.Api.YoutubeModel.Old ->
            Evergreen.V71.Api.YoutubeModel.Old

        Evergreen.V66.Api.YoutubeModel.Live ->
            Evergreen.V71.Api.YoutubeModel.Live

        Evergreen.V66.Api.YoutubeModel.Ended p0 ->
            Evergreen.V71.Api.YoutubeModel.Ended p0

        Evergreen.V66.Api.YoutubeModel.Impossibru ->
            Evergreen.V71.Api.YoutubeModel.Impossibru


migrate_Api_YoutubeModel_Video : Evergreen.V66.Api.YoutubeModel.Video -> Evergreen.V71.Api.YoutubeModel.Video
migrate_Api_YoutubeModel_Video old =
    { id = old.id
    , title = old.title
    , description = old.description
    , videoOwnerChannelId = old.videoOwnerChannelId
    , videoOwnerChannelTitle = old.videoOwnerChannelTitle
    , playlistId = old.playlistId
    , thumbnailUrl = old.thumbnailUrl
    , publishedAt = old.publishedAt
    , liveChatId = old.liveChatId
    , liveStatus = old.liveStatus |> migrate_Api_YoutubeModel_LiveStatus
    , statsOnConclusion = old.statsOnConclusion
    , statsAfter24Hours = old.statsAfter24Hours
    , reportAfter24Hours = old.reportAfter24Hours
    , chatMsgCount = old.chatMsgCount
    , ctr = old.ctr
    , liveViews = old.liveViews
    }


migrate_Types_BackendMsg : Evergreen.V66.Types.BackendMsg -> Evergreen.V71.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V66.Types.OnConnect p0 p1 ->
            Evergreen.V71.Types.OnConnect p0 p1

        Evergreen.V66.Types.AuthenticateSession p0 p1 p2 p3 ->
            Evergreen.V71.Types.AuthenticateSession p0 p1 (p2 |> migrate_Api_User_User) p3

        Evergreen.V66.Types.VerifySession p0 p1 p2 ->
            Evergreen.V71.Types.VerifySession p0 p1 p2

        Evergreen.V66.Types.RegisterUser p0 p1 p2 p3 ->
            Evergreen.V71.Types.RegisterUser p0 p1 p2 p3

        Evergreen.V66.Types.Log_ p0 p1 p2 ->
            Evergreen.V71.Types.Log_ p0 (p1 |> migrate_Api_Logging_LogLevel) p2

        Evergreen.V66.Types.GotFreshAccessTokenWithTime p0 p1 p2 ->
            Evergreen.V71.Types.GotFreshAccessTokenWithTime p0 p1 p2

        Evergreen.V66.Types.Batch_RefreshAccessTokens p0 ->
            Evergreen.V71.Types.Batch_RefreshAccessTokens p0

        Evergreen.V66.Types.Batch_RefreshAllChannels p0 ->
            Evergreen.V71.Types.Batch_RefreshAllChannels p0

        Evergreen.V66.Types.Batch_RefreshAllPlaylists p0 ->
            Evergreen.V71.Types.Batch_RefreshAllPlaylists p0

        Evergreen.V66.Types.Batch_RefreshAllVideosFromPlaylists p0 ->
            Evergreen.V71.Types.Batch_RefreshAllVideosFromPlaylists p0

        Evergreen.V66.Types.Batch_GetLiveVideoStreamData p0 ->
            Evergreen.V71.Types.Batch_GetLiveVideoStreamData p0

        Evergreen.V66.Types.Batch_GetChatMessages p0 ->
            Evergreen.V71.Types.Batch_GetChatMessages p0

        Evergreen.V66.Types.Batch_GetVideoStats p0 ->
            Evergreen.V71.Types.Batch_GetVideoStats p0

        Evergreen.V66.Types.Batch_GetVideoDailyReports p0 ->
            Evergreen.V71.Types.Batch_GetVideoDailyReports p0

        Evergreen.V66.Types.Batch_GetVideoStatisticsAtTime p0 ->
            Evergreen.V71.Types.Batch_GetVideoStatisticsAtTime p0

        Evergreen.V66.Types.Batch_GetCompetitorChannelIds p0 ->
            Evergreen.V71.Types.Batch_GetCompetitorChannelIds p0

        Evergreen.V66.Types.Batch_GetCompetitorVideos p0 ->
            Evergreen.V71.Types.Batch_GetCompetitorVideos p0

        Evergreen.V66.Types.Batch_ExportToSheet p0 ->
            Evergreen.V71.Types.Batch_ExportToSheet p0

        Evergreen.V66.Types.GetChannelId p0 ->
            Evergreen.V71.Types.GetChannelId p0

        Evergreen.V66.Types.GetAccessToken p0 p1 ->
            Evergreen.V71.Types.GetAccessToken p0 p1

        Evergreen.V66.Types.GotAccessToken p0 p1 p2 ->
            Evergreen.V71.Types.GotAccessToken p0 p1 p2

        Evergreen.V66.Types.GetChannelsByCredential p0 ->
            Evergreen.V71.Types.GetChannelsByCredential p0

        Evergreen.V66.Types.GotChannels p0 p1 ->
            Evergreen.V71.Types.GotChannels p0 p1

        Evergreen.V66.Types.GetPlaylistsByChannel p0 ->
            Evergreen.V71.Types.GetPlaylistsByChannel p0

        Evergreen.V66.Types.GotPlaylists p0 p1 ->
            Evergreen.V71.Types.GotPlaylists p0 p1

        Evergreen.V66.Types.GetVideosByPlaylist p0 p1 ->
            Evergreen.V71.Types.GetVideosByPlaylist p0 p1

        Evergreen.V66.Types.GotVideosFromPlaylist p0 p1 ->
            Evergreen.V71.Types.GotVideosFromPlaylist p0 p1

        Evergreen.V66.Types.GotLiveVideoStreamData p0 p1 p2 ->
            Evergreen.V71.Types.GotLiveVideoStreamData p0 p1 p2

        Evergreen.V66.Types.GotVideoStatsOnConclusion p0 p1 p2 ->
            Evergreen.V71.Types.GotVideoStatsOnConclusion p0 p1 p2

        Evergreen.V66.Types.GotVideoStatsAfter24Hrs p0 p1 p2 ->
            Evergreen.V71.Types.GotVideoStatsAfter24Hrs p0 p1 p2

        Evergreen.V66.Types.GotVideoStatsOnTheHour p0 p1 p2 ->
            Evergreen.V71.Types.GotVideoStatsOnTheHour p0 p1 p2

        Evergreen.V66.Types.GotChatMessages p0 p1 ->
            Evergreen.V71.Types.GotChatMessages p0 p1

        Evergreen.V66.Types.GotVideoDailyReport p0 p1 ->
            Evergreen.V71.Types.GotVideoDailyReport p0 p1

        Evergreen.V66.Types.GotChannelId p0 p1 ->
            Evergreen.V71.Types.GotChannelId p0 p1

        Evergreen.V66.Types.GotCompetitorVideos p0 p1 ->
            Evergreen.V71.Types.GotCompetitorVideos p0 p1

        Evergreen.V66.Types.SheetUpdated p0 p1 p2 p3 ->
            Evergreen.V71.Types.SheetUpdated p0 p1 (p2 |> migrate_Types_NextAction) p3

        Evergreen.V66.Types.DeletedSheets p0 p1 p2 p3 ->
            Evergreen.V71.Types.DeletedSheets p0 p1 (p2 |> migrate_Types_NextAction) p3

        Evergreen.V66.Types.GotSheetIds p0 p1 p2 ->
            Evergreen.V71.Types.GotSheetIds p0 (p1 |> migrate_Types_NextAction) p2

        Evergreen.V66.Types.AddedSheets p0 p1 p2 p3 ->
            Evergreen.V71.Types.AddedSheets p0 p1 (p2 |> migrate_Types_NextAction) p3

        Evergreen.V66.Types.NoOpBackendMsg ->
            Evergreen.V71.Types.NoOpBackendMsg



migrate_Types_NextAction : Evergreen.V66.Types.NextAction -> Evergreen.V71.Types.NextAction
migrate_Types_NextAction old =
    case old of
        Evergreen.V66.Types.DeleteSheets ->
            Evergreen.V71.Types.DeleteSheets

        Evergreen.V66.Types.AddSheets p0 ->
            Evergreen.V71.Types.AddSheets p0

        Evergreen.V66.Types.UpdateSheets p0 ->
            Evergreen.V71.Types.UpdateSheets p0

        Evergreen.V66.Types.Done ->
            Evergreen.V71.Types.Done
