module Evergreen.Migrate.V77 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V71.Api.YoutubeModel
import Evergreen.V71.Bridge
import Evergreen.V71.Types
import Evergreen.V77.Api.YoutubeModel
import Evergreen.V77.Bridge
import Evergreen.V77.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V71.Types.FrontendModel -> ModelMigration Evergreen.V77.Types.FrontendModel Evergreen.V77.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V71.Types.BackendModel -> ModelMigration Evergreen.V77.Types.BackendModel Evergreen.V77.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V71.Types.FrontendMsg -> MsgMigration Evergreen.V77.Types.FrontendMsg Evergreen.V77.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V71.Types.ToBackend -> MsgMigration Evergreen.V77.Types.ToBackend Evergreen.V77.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V71.Types.BackendMsg -> MsgMigration Evergreen.V77.Types.BackendMsg Evergreen.V77.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V71.Types.ToFrontend -> MsgMigration Evergreen.V77.Types.ToFrontend Evergreen.V77.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_ToBackend : Evergreen.V71.Types.ToBackend -> Evergreen.V77.Types.ToBackend
migrate_Types_ToBackend old =
    old |> migrate_Bridge_ToBackend


migrate_Api_YoutubeModel_DaysOfWeek : Evergreen.V71.Api.YoutubeModel.DaysOfWeek -> Evergreen.V77.Api.YoutubeModel.DaysOfWeek
migrate_Api_YoutubeModel_DaysOfWeek old =
    old


migrate_Api_YoutubeModel_Playlist : Evergreen.V71.Api.YoutubeModel.Playlist -> Evergreen.V77.Api.YoutubeModel.Playlist
migrate_Api_YoutubeModel_Playlist old =
    old


migrate_Api_YoutubeModel_Schedule : Evergreen.V71.Api.YoutubeModel.Schedule -> Evergreen.V77.Api.YoutubeModel.Schedule
migrate_Api_YoutubeModel_Schedule old =
    { playlistId = old.playlistId
    , hour = old.hour
    , minute = old.minute
    , days = old.days |> migrate_Api_YoutubeModel_DaysOfWeek
    }


migrate_Bridge_ToBackend : Evergreen.V71.Bridge.ToBackend -> Evergreen.V77.Bridge.ToBackend
migrate_Bridge_ToBackend old =
    case old of
        Evergreen.V71.Bridge.AttemptRegistration p0 ->
            Evergreen.V77.Bridge.AttemptRegistration p0

        Evergreen.V71.Bridge.AttemptSignIn p0 ->
            Evergreen.V77.Bridge.AttemptSignIn p0

        Evergreen.V71.Bridge.AttemptSignOut ->
            Evergreen.V77.Bridge.AttemptSignOut

        Evergreen.V71.Bridge.AttemptGetCredentials ->
            Evergreen.V77.Bridge.AttemptGetCredentials

        Evergreen.V71.Bridge.AttemptGetChannels p0 ->
            Evergreen.V77.Bridge.AttemptGetChannels p0

        Evergreen.V71.Bridge.AttemptGetVideos p0 ->
            Evergreen.V77.Bridge.AttemptGetVideos p0

        Evergreen.V71.Bridge.AttemptYeetCredentials p0 ->
            Evergreen.V77.Bridge.AttemptYeetCredentials p0

        Evergreen.V71.Bridge.FetchChannelsFromYoutube p0 ->
            Evergreen.V77.Bridge.FetchChannelsFromYoutube p0

        Evergreen.V71.Bridge.FetchPlaylistsFromYoutube p0 ->
            Evergreen.V77.Bridge.FetchPlaylistsFromYoutube p0

        Evergreen.V71.Bridge.FetchVideosFromYoutube p0 ->
            Evergreen.V77.Bridge.FetchVideosFromYoutube p0

        Evergreen.V71.Bridge.AttemptUpdateVideoCtr p0 p1 ->
            Evergreen.V77.Bridge.AttemptUpdateVideoCtr p0 p1

        Evergreen.V71.Bridge.AttemptUpdateVideoLiveViews p0 p1 ->
            Evergreen.V77.Bridge.AttemptUpdateVideoLiveViews p0 p1

        Evergreen.V71.Bridge.AttemptGetChannelAndPlaylists p0 ->
            Evergreen.V77.Bridge.AttemptGetChannelAndPlaylists p0

        Evergreen.V71.Bridge.AttemptGetLogs p0 p1 ->
            Evergreen.V77.Bridge.AttemptGetLogs p0 p1

        Evergreen.V71.Bridge.AttemptYeetLogs ->
            Evergreen.V77.Bridge.AttemptYeetLogs

        Evergreen.V71.Bridge.AttemptYeetVideos ->
            Evergreen.V77.Bridge.AttemptYeetVideos

        Evergreen.V71.Bridge.AttemptGetVideoDetails p0 ->
            Evergreen.V77.Bridge.AttemptGetVideoDetails p0

        Evergreen.V71.Bridge.AttemptBatch_RefreshAccessTokens ->
            Evergreen.V77.Bridge.AttemptBatch_RefreshAccessTokens

        Evergreen.V71.Bridge.AttemptBatch_RefreshAllChannels ->
            Evergreen.V77.Bridge.AttemptBatch_RefreshAllChannels

        Evergreen.V71.Bridge.AttemptBatch_RefreshAllPlaylists ->
            Evergreen.V77.Bridge.AttemptBatch_RefreshAllPlaylists

        Evergreen.V71.Bridge.AttemptBatch_RefreshAllVideosFromPlaylists ->
            Evergreen.V77.Bridge.AttemptBatch_RefreshAllVideosFromPlaylists

        Evergreen.V71.Bridge.AttemptBatch_GetLiveVideoStreamData ->
            Evergreen.V77.Bridge.AttemptBatch_GetLiveVideoStreamData

        Evergreen.V71.Bridge.AttemptBatch_GetVideoStats ->
            Evergreen.V77.Bridge.AttemptBatch_GetVideoStats

        Evergreen.V71.Bridge.AttemptBatch_GetVideoDailyReports ->
            Evergreen.V77.Bridge.AttemptBatch_GetVideoDailyReports

        Evergreen.V71.Bridge.AttemptBatch_GetChatMessages ->
            Evergreen.V77.Bridge.AttemptBatch_GetChatMessages

        Evergreen.V71.Bridge.AttemptBatch_GetVideoStatisticsAtTime ->
            Evergreen.V77.Bridge.AttemptBatch_GetVideoStatisticsAtTime

        Evergreen.V71.Bridge.AttemptBatch_GetCompetitorVideos ->
            Evergreen.V77.Bridge.AttemptBatch_GetCompetitorVideos

        Evergreen.V71.Bridge.AttemptBatch_ExportToSheet ->
            Evergreen.V77.Bridge.AttemptBatch_ExportToSheet

        Evergreen.V71.Bridge.AttemptFixData ->
            Evergreen.V77.Bridge.NoOpToBackend

        Evergreen.V71.Bridge.UpdateSchedule p0 ->
            Evergreen.V77.Bridge.UpdateSchedule (p0 |> migrate_Api_YoutubeModel_Schedule)

        Evergreen.V71.Bridge.UpdatePlaylist p0 ->
            Evergreen.V77.Bridge.UpdatePlaylist (p0 |> migrate_Api_YoutubeModel_Playlist)

        Evergreen.V71.Bridge.NoOpToBackend ->
            Evergreen.V77.Bridge.NoOpToBackend
