module Evergreen.Migrate.V78 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V77.Api.Data
import Evergreen.V77.Api.Logging
import Evergreen.V77.Api.User
import Evergreen.V77.Api.YoutubeModel
import Evergreen.V77.Gen.Msg
import Evergreen.V77.Gen.Pages
import Evergreen.V77.Pages.Admin
import Evergreen.V77.Pages.Channel.Id_
import Evergreen.V77.Pages.End
import Evergreen.V77.Pages.Example
import Evergreen.V77.Pages.Ga.Email_
import Evergreen.V77.Pages.Home_
import Evergreen.V77.Pages.Log
import Evergreen.V77.Pages.Login
import Evergreen.V77.Pages.Playlist.Id_
import Evergreen.V77.Pages.Register
import Evergreen.V77.Pages.Video.Id_
import Evergreen.V77.Shared
import Evergreen.V77.Types
import Evergreen.V78.Api.Data
import Evergreen.V78.Api.Logging
import Evergreen.V78.Api.User
import Evergreen.V78.Api.YoutubeModel
import Evergreen.V78.Gen.Msg
import Evergreen.V78.Gen.Pages
import Evergreen.V78.Pages.Admin
import Evergreen.V78.Pages.Channel.Id_
import Evergreen.V78.Pages.End
import Evergreen.V78.Pages.Example
import Evergreen.V78.Pages.Ga.Email_
import Evergreen.V78.Pages.Home_
import Evergreen.V78.Pages.Log
import Evergreen.V78.Pages.Login
import Evergreen.V78.Pages.Playlist.Id_
import Evergreen.V78.Pages.Register
import Evergreen.V78.Pages.Video.Id_
import Evergreen.V78.Shared
import Evergreen.V78.Types
import Lamdera.Migrations exposing (..)
import Maybe


frontendModel : Evergreen.V77.Types.FrontendModel -> ModelMigration Evergreen.V78.Types.FrontendModel Evergreen.V78.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V77.Types.BackendModel -> ModelMigration Evergreen.V78.Types.BackendModel Evergreen.V78.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V77.Types.FrontendMsg -> MsgMigration Evergreen.V78.Types.FrontendMsg Evergreen.V78.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V77.Types.ToBackend -> MsgMigration Evergreen.V78.Types.ToBackend Evergreen.V78.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V77.Types.BackendMsg -> MsgMigration Evergreen.V78.Types.BackendMsg Evergreen.V78.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V77.Types.ToFrontend -> MsgMigration Evergreen.V78.Types.ToFrontend Evergreen.V78.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Api_Data_Data : (value_old -> value_new) -> Evergreen.V77.Api.Data.Data value_old -> Evergreen.V78.Api.Data.Data value_new
migrate_Api_Data_Data migrate_value old =
    case old of
        Evergreen.V77.Api.Data.NotAsked ->
            Evergreen.V78.Api.Data.NotAsked

        Evergreen.V77.Api.Data.Loading ->
            Evergreen.V78.Api.Data.Loading

        Evergreen.V77.Api.Data.Failure p0 ->
            Evergreen.V78.Api.Data.Failure p0

        Evergreen.V77.Api.Data.Success p0 ->
            Evergreen.V78.Api.Data.Success (p0 |> migrate_value)


migrate_Api_Logging_LogEntry : Evergreen.V77.Api.Logging.LogEntry -> Evergreen.V78.Api.Logging.LogEntry
migrate_Api_Logging_LogEntry old =
    { message = old.message
    , timestamp = old.timestamp
    , logLevel = old.logLevel |> migrate_Api_Logging_LogLevel
    }


migrate_Api_Logging_LogLevel : Evergreen.V77.Api.Logging.LogLevel -> Evergreen.V78.Api.Logging.LogLevel
migrate_Api_Logging_LogLevel old =
    case old of
        Evergreen.V77.Api.Logging.Error ->
            Evergreen.V78.Api.Logging.Error

        Evergreen.V77.Api.Logging.Info ->
            Evergreen.V78.Api.Logging.Info

        Evergreen.V77.Api.Logging.Alert ->
            Evergreen.V78.Api.Logging.Alert


migrate_Api_User_Role : Evergreen.V77.Api.User.Role -> Evergreen.V78.Api.User.Role
migrate_Api_User_Role old =
    case old of
        Evergreen.V77.Api.User.Basic ->
            Evergreen.V78.Api.User.Basic

        Evergreen.V77.Api.User.Editor ->
            Evergreen.V78.Api.User.Editor

        Evergreen.V77.Api.User.Admin ->
            Evergreen.V78.Api.User.Admin


migrate_Api_User_User : Evergreen.V77.Api.User.User -> Evergreen.V78.Api.User.User
migrate_Api_User_User old =
    { email = old.email
    , role = old.role |> migrate_Api_User_Role
    }


migrate_Api_YoutubeModel_Channel : Evergreen.V77.Api.YoutubeModel.Channel -> Evergreen.V78.Api.YoutubeModel.Channel
migrate_Api_YoutubeModel_Channel old =
    old


migrate_Api_YoutubeModel_DaysOfWeek : Evergreen.V77.Api.YoutubeModel.DaysOfWeek -> Evergreen.V78.Api.YoutubeModel.DaysOfWeek
migrate_Api_YoutubeModel_DaysOfWeek old =
    old


migrate_Api_YoutubeModel_LiveStatus : Evergreen.V77.Api.YoutubeModel.LiveStatus -> Evergreen.V78.Api.YoutubeModel.LiveStatus
migrate_Api_YoutubeModel_LiveStatus old =
    case old of
        Evergreen.V77.Api.YoutubeModel.Unknown ->
            Evergreen.V78.Api.YoutubeModel.Unknown

        Evergreen.V77.Api.YoutubeModel.Uploaded ->
            Evergreen.V78.Api.YoutubeModel.Uploaded

        Evergreen.V77.Api.YoutubeModel.Scheduled p0 ->
            Evergreen.V78.Api.YoutubeModel.Scheduled p0

        Evergreen.V77.Api.YoutubeModel.Expired ->
            Evergreen.V78.Api.YoutubeModel.Expired

        Evergreen.V77.Api.YoutubeModel.Old ->
            Evergreen.V78.Api.YoutubeModel.Old

        Evergreen.V77.Api.YoutubeModel.Live ->
            Evergreen.V78.Api.YoutubeModel.Live

        Evergreen.V77.Api.YoutubeModel.Ended p0 ->
            Evergreen.V78.Api.YoutubeModel.Ended p0

        Evergreen.V77.Api.YoutubeModel.Impossibru ->
            Evergreen.V78.Api.YoutubeModel.Impossibru


migrate_Api_YoutubeModel_Playlist : Evergreen.V77.Api.YoutubeModel.Playlist -> Evergreen.V78.Api.YoutubeModel.Playlist
migrate_Api_YoutubeModel_Playlist old =
    old


migrate_Api_YoutubeModel_Schedule : Evergreen.V77.Api.YoutubeModel.Schedule -> Evergreen.V78.Api.YoutubeModel.Schedule
migrate_Api_YoutubeModel_Schedule old =
    { playlistId = old.playlistId
    , hour = old.hour
    , minute = old.minute
    , days = old.days |> migrate_Api_YoutubeModel_DaysOfWeek
    }


migrate_Api_YoutubeModel_Video : Evergreen.V77.Api.YoutubeModel.Video -> Evergreen.V78.Api.YoutubeModel.Video
migrate_Api_YoutubeModel_Video old =
    { id = old.id
    , title = old.title
    , description = old.description
    , videoOwnerChannelId = old.videoOwnerChannelId
    , videoOwnerChannelTitle = old.videoOwnerChannelTitle
    , playlistId = old.playlistId
    , thumbnailUrl = old.thumbnailUrl
    , publishedAt = old.publishedAt
    , liveChatId = old.liveChatId
    , liveStatus = old.liveStatus |> migrate_Api_YoutubeModel_LiveStatus
    , statsOnConclusion = old.statsOnConclusion
    , statsAfter24Hours = old.statsAfter24Hours
    , reportAfter24Hours = old.reportAfter24Hours
    , chatMsgCount = old.chatMsgCount
    , ctr = old.ctr
    , liveViews = old.liveViews
    }


migrate_Api_YoutubeModel_VideoResults : Evergreen.V77.Api.YoutubeModel.VideoResults -> Evergreen.V78.Api.YoutubeModel.VideoResults
migrate_Api_YoutubeModel_VideoResults old =
    { playlists = old.playlists
    , videos = old.videos |> Dict.map (\k -> migrate_Api_YoutubeModel_Video)
    , liveVideoDetails = old.liveVideoDetails
    , currentViewers = old.currentViewers
    , videoChannels = old.videoChannels
    , videoStats = old.videoStats
    , competitorVideos = old.competitorVideos |> Dict.map (\k -> Dict.map (\k2 -> migrate_Api_YoutubeModel_Video))
    , competitorsVsUs = Dict.empty
    }


migrate_Gen_Msg_Msg : Evergreen.V77.Gen.Msg.Msg -> Evergreen.V78.Gen.Msg.Msg
migrate_Gen_Msg_Msg old =
    case old of
        Evergreen.V77.Gen.Msg.Admin p0 ->
            Evergreen.V78.Gen.Msg.Admin (p0 |> migrate_Pages_Admin_Msg)

        Evergreen.V77.Gen.Msg.End p0 ->
            Evergreen.V78.Gen.Msg.End (p0 |> migrate_Pages_End_Msg)

        Evergreen.V77.Gen.Msg.Example p0 ->
            Evergreen.V78.Gen.Msg.Example (p0 |> migrate_Pages_Example_Msg)

        Evergreen.V77.Gen.Msg.Home_ p0 ->
            Evergreen.V78.Gen.Msg.Home_ (p0 |> migrate_Pages_Home__Msg)

        Evergreen.V77.Gen.Msg.Log p0 ->
            Evergreen.V78.Gen.Msg.Log (p0 |> migrate_Pages_Log_Msg)

        Evergreen.V77.Gen.Msg.Login p0 ->
            Evergreen.V78.Gen.Msg.Login (p0 |> migrate_Pages_Login_Msg)

        Evergreen.V77.Gen.Msg.Register p0 ->
            Evergreen.V78.Gen.Msg.Register (p0 |> migrate_Pages_Register_Msg)

        Evergreen.V77.Gen.Msg.Channel__Id_ p0 ->
            Evergreen.V78.Gen.Msg.Channel__Id_ (p0 |> migrate_Pages_Channel_Id__Msg)

        Evergreen.V77.Gen.Msg.Ga__Email_ p0 ->
            Evergreen.V78.Gen.Msg.Ga__Email_ (p0 |> migrate_Pages_Ga_Email__Msg)

        Evergreen.V77.Gen.Msg.Playlist__Id_ p0 ->
            Evergreen.V78.Gen.Msg.Playlist__Id_ (p0 |> migrate_Pages_Playlist_Id__Msg)

        Evergreen.V77.Gen.Msg.Video__Id_ p0 ->
            Evergreen.V78.Gen.Msg.Video__Id_ (p0 |> migrate_Pages_Video_Id__Msg)


migrate_Gen_Pages_Msg : Evergreen.V77.Gen.Pages.Msg -> Evergreen.V78.Gen.Pages.Msg
migrate_Gen_Pages_Msg old =
    old |> migrate_Gen_Msg_Msg


migrate_Pages_Admin_Msg : Evergreen.V77.Pages.Admin.Msg -> Evergreen.V78.Pages.Admin.Msg
migrate_Pages_Admin_Msg old =
    case old of
        Evergreen.V77.Pages.Admin.ReplaceMe ->
            Evergreen.V78.Pages.Admin.ReplaceMe


migrate_Pages_Channel_Id__Msg : Evergreen.V77.Pages.Channel.Id_.Msg -> Evergreen.V78.Pages.Channel.Id_.Msg
migrate_Pages_Channel_Id__Msg old =
    case old of
        Evergreen.V77.Pages.Channel.Id_.GotChannelAndPlaylists p0 p1 p2 p3 ->
            Evergreen.V78.Pages.Channel.Id_.GotChannelAndPlaylists (p0 |> migrate_Api_YoutubeModel_Channel) p1 p2 p3

        Evergreen.V77.Pages.Channel.Id_.GetPlaylists ->
            Evergreen.V78.Pages.Channel.Id_.GetPlaylists

        Evergreen.V77.Pages.Channel.Id_.Schedule_UpdateSchedule p0 ->
            Evergreen.V78.Pages.Channel.Id_.Schedule_UpdateSchedule (p0 |> migrate_Api_YoutubeModel_Schedule)

        Evergreen.V77.Pages.Channel.Id_.MonitorPlaylist p0 p1 ->
            Evergreen.V78.Pages.Channel.Id_.MonitorPlaylist (p0 |> migrate_Api_YoutubeModel_Playlist) p1

        Evergreen.V77.Pages.Channel.Id_.Competitors p0 p1 ->
            Evergreen.V78.Pages.Channel.Id_.Competitors (p0 |> migrate_Api_YoutubeModel_Playlist) p1


migrate_Pages_End_Msg : Evergreen.V77.Pages.End.Msg -> Evergreen.V78.Pages.End.Msg
migrate_Pages_End_Msg old =
    case old of
        Evergreen.V77.Pages.End.ReplaceMe ->
            Evergreen.V78.Pages.End.ReplaceMe


migrate_Pages_Example_Msg : Evergreen.V77.Pages.Example.Msg -> Evergreen.V78.Pages.Example.Msg
migrate_Pages_Example_Msg old =
    case old of
        Evergreen.V77.Pages.Example.GotCredentials p0 ->
            Evergreen.V78.Pages.Example.GotCredentials p0

        Evergreen.V77.Pages.Example.GetChannels p0 ->
            Evergreen.V78.Pages.Example.GetChannels p0

        Evergreen.V77.Pages.Example.Yeet p0 ->
            Evergreen.V78.Pages.Example.Yeet p0

        Evergreen.V77.Pages.Example.Tick p0 ->
            Evergreen.V78.Pages.Example.Tick p0


migrate_Pages_Ga_Email__Msg : Evergreen.V77.Pages.Ga.Email_.Msg -> Evergreen.V78.Pages.Ga.Email_.Msg
migrate_Pages_Ga_Email__Msg old =
    case old of
        Evergreen.V77.Pages.Ga.Email_.GotChannels p0 ->
            Evergreen.V78.Pages.Ga.Email_.GotChannels p0

        Evergreen.V77.Pages.Ga.Email_.GetChannels ->
            Evergreen.V78.Pages.Ga.Email_.GetChannels


migrate_Pages_Home__Msg : Evergreen.V77.Pages.Home_.Msg -> Evergreen.V78.Pages.Home_.Msg
migrate_Pages_Home__Msg old =
    case old of
        Evergreen.V77.Pages.Home_.Noop ->
            Evergreen.V78.Pages.Home_.Noop


migrate_Pages_Log_Msg : Evergreen.V77.Pages.Log.Msg -> Evergreen.V78.Pages.Log.Msg
migrate_Pages_Log_Msg old =
    case old of
        Evergreen.V77.Pages.Log.GotLogs p0 p1 ->
            Evergreen.V78.Pages.Log.GotLogs p0 (p1 |> List.map migrate_Api_Logging_LogEntry)

        Evergreen.V77.Pages.Log.GetLogPage p0 p1 ->
            Evergreen.V78.Pages.Log.GetLogPage p0 p1

        Evergreen.V77.Pages.Log.YeetLogs ->
            Evergreen.V78.Pages.Log.YeetLogs

        Evergreen.V77.Pages.Log.YeetVideos ->
            Evergreen.V78.Pages.Log.YeetVideos

        Evergreen.V77.Pages.Log.Batch_RefreshAccessTokens ->
            Evergreen.V78.Pages.Log.Batch_RefreshAccessTokens

        Evergreen.V77.Pages.Log.Batch_RefreshAllChannels ->
            Evergreen.V78.Pages.Log.Batch_RefreshAllChannels

        Evergreen.V77.Pages.Log.Batch_RefreshAllPlaylists ->
            Evergreen.V78.Pages.Log.Batch_RefreshAllPlaylists

        Evergreen.V77.Pages.Log.Batch_RefreshAllVideosFromPlaylists ->
            Evergreen.V78.Pages.Log.Batch_RefreshAllVideosFromPlaylists

        Evergreen.V77.Pages.Log.Batch_GetLiveVideoStreamData ->
            Evergreen.V78.Pages.Log.Batch_GetLiveVideoStreamData

        Evergreen.V77.Pages.Log.Batch_GetVideoStats ->
            Evergreen.V78.Pages.Log.Batch_GetVideoStats

        Evergreen.V77.Pages.Log.Batch_GetVideoDailyReports ->
            Evergreen.V78.Pages.Log.Batch_GetVideoDailyReports

        Evergreen.V77.Pages.Log.Batch_GetChatMessages ->
            Evergreen.V78.Pages.Log.Batch_GetChatMessages

        Evergreen.V77.Pages.Log.Batch_GetVideoStatisticsAtTime ->
            Evergreen.V78.Pages.Log.Batch_GetVideoStatisticsAtTime

        Evergreen.V77.Pages.Log.Batch_GetCompetitorVideos ->
            Evergreen.V78.Pages.Log.Batch_GetCompetitorVideos

        Evergreen.V77.Pages.Log.Batch_ExportToSheet ->
            Evergreen.V78.Pages.Log.Batch_ExportToSheet

        Evergreen.V77.Pages.Log.FixData ->
            Evergreen.V78.Pages.Log.FixData


migrate_Pages_Login_Field : Evergreen.V77.Pages.Login.Field -> Evergreen.V78.Pages.Login.Field
migrate_Pages_Login_Field old =
    case old of
        Evergreen.V77.Pages.Login.Email ->
            Evergreen.V78.Pages.Login.Email

        Evergreen.V77.Pages.Login.Password ->
            Evergreen.V78.Pages.Login.Password


migrate_Pages_Login_Msg : Evergreen.V77.Pages.Login.Msg -> Evergreen.V78.Pages.Login.Msg
migrate_Pages_Login_Msg old =
    case old of
        Evergreen.V77.Pages.Login.Updated p0 p1 ->
            Evergreen.V78.Pages.Login.Updated (p0 |> migrate_Pages_Login_Field) p1

        Evergreen.V77.Pages.Login.ToggledShowPassword ->
            Evergreen.V78.Pages.Login.ToggledShowPassword

        Evergreen.V77.Pages.Login.ClickedSubmit ->
            Evergreen.V78.Pages.Login.ClickedSubmit

        Evergreen.V77.Pages.Login.GotUser p0 ->
            Evergreen.V78.Pages.Login.GotUser (p0 |> migrate_Api_Data_Data migrate_Api_User_User)


migrate_Pages_Playlist_Id__Msg : Evergreen.V77.Pages.Playlist.Id_.Msg -> Evergreen.V78.Pages.Playlist.Id_.Msg
migrate_Pages_Playlist_Id__Msg old =
    case old of
        Evergreen.V77.Pages.Playlist.Id_.GotVideos p0 ->
            Evergreen.V78.Pages.Playlist.Id_.GotVideos (p0 |> migrate_Api_YoutubeModel_VideoResults)

        Evergreen.V77.Pages.Playlist.Id_.GetVideos ->
            Evergreen.V78.Pages.Playlist.Id_.GetVideos

        Evergreen.V77.Pages.Playlist.Id_.UpdateVideoCTR p0 p1 ->
            Evergreen.V78.Pages.Playlist.Id_.UpdateVideoCTR p0 p1

        Evergreen.V77.Pages.Playlist.Id_.UpdateVideoLiveViews p0 p1 ->
            Evergreen.V78.Pages.Playlist.Id_.UpdateVideoLiveViews p0 p1

        Evergreen.V77.Pages.Playlist.Id_.Tick p0 ->
            Evergreen.V78.Pages.Playlist.Id_.Tick p0


migrate_Pages_Register_Field : Evergreen.V77.Pages.Register.Field -> Evergreen.V78.Pages.Register.Field
migrate_Pages_Register_Field old =
    case old of
        Evergreen.V77.Pages.Register.Email ->
            Evergreen.V78.Pages.Register.Email

        Evergreen.V77.Pages.Register.Password ->
            Evergreen.V78.Pages.Register.Password


migrate_Pages_Register_Msg : Evergreen.V77.Pages.Register.Msg -> Evergreen.V78.Pages.Register.Msg
migrate_Pages_Register_Msg old =
    case old of
        Evergreen.V77.Pages.Register.Updated p0 p1 ->
            Evergreen.V78.Pages.Register.Updated (p0 |> migrate_Pages_Register_Field) p1

        Evergreen.V77.Pages.Register.ToggledShowPassword ->
            Evergreen.V78.Pages.Register.ToggledShowPassword

        Evergreen.V77.Pages.Register.ClickedSubmit ->
            Evergreen.V78.Pages.Register.ClickedSubmit

        Evergreen.V77.Pages.Register.GotUser p0 ->
            Evergreen.V78.Pages.Register.GotUser (p0 |> migrate_Api_Data_Data migrate_Api_User_User)


migrate_Pages_Video_Id__Model : Evergreen.V77.Pages.Video.Id_.Model -> Evergreen.V78.Pages.Video.Id_.Model
migrate_Pages_Video_Id__Model old =
    { channelTitle = old.channelTitle
    , playlistTitle = old.playlistTitle
    , video = old.video |> Maybe.map migrate_Api_YoutubeModel_Video
    , liveVideoDetails = old.liveVideoDetails
    , currentViewers = old.currentViewers
    , videoStatisticsAtTime = old.videoStatisticsAtTime
    }


migrate_Pages_Video_Id__Msg : Evergreen.V77.Pages.Video.Id_.Msg -> Evergreen.V78.Pages.Video.Id_.Msg
migrate_Pages_Video_Id__Msg old =
    case old of
        Evergreen.V77.Pages.Video.Id_.ReplaceMe ->
            Evergreen.V78.Pages.Video.Id_.ReplaceMe

        Evergreen.V77.Pages.Video.Id_.GotVideoDetails p0 ->
            Evergreen.V78.Pages.Video.Id_.GotVideoDetails (p0 |> migrate_Pages_Video_Id__Model)


migrate_Shared_Msg : Evergreen.V77.Shared.Msg -> Evergreen.V78.Shared.Msg
migrate_Shared_Msg old =
    case old of
        Evergreen.V77.Shared.GotViewWidth p0 ->
            Evergreen.V78.Shared.GotViewWidth p0

        Evergreen.V77.Shared.Noop ->
            Evergreen.V78.Shared.Noop

        Evergreen.V77.Shared.SignInUser p0 ->
            Evergreen.V78.Shared.SignInUser (p0 |> migrate_Api_User_User)

        Evergreen.V77.Shared.SignOutUser ->
            Evergreen.V78.Shared.SignOutUser

        Evergreen.V77.Shared.ShowToastMessage p0 ->
            Evergreen.V78.Shared.ShowToastMessage p0

        Evergreen.V77.Shared.HideToastMessage p0 ->
            Evergreen.V78.Shared.HideToastMessage p0


migrate_Types_FrontendMsg : Evergreen.V77.Types.FrontendMsg -> Evergreen.V78.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V77.Types.ChangedUrl p0 ->
            Evergreen.V78.Types.ChangedUrl p0

        Evergreen.V77.Types.ClickedLink p0 ->
            Evergreen.V78.Types.ClickedLink p0

        Evergreen.V77.Types.Shared p0 ->
            Evergreen.V78.Types.Shared (p0 |> migrate_Shared_Msg)

        Evergreen.V77.Types.Page p0 ->
            Evergreen.V78.Types.Page (p0 |> migrate_Gen_Pages_Msg)

        Evergreen.V77.Types.Noop ->
            Evergreen.V78.Types.Noop


migrate_Types_ToFrontend : Evergreen.V77.Types.ToFrontend -> Evergreen.V78.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V77.Types.PageMsg p0 ->
            Evergreen.V78.Types.PageMsg (p0 |> migrate_Gen_Pages_Msg)

        Evergreen.V77.Types.SharedMsg p0 ->
            Evergreen.V78.Types.SharedMsg (p0 |> migrate_Shared_Msg)

        Evergreen.V77.Types.NoOpToFrontend ->
            Evergreen.V78.Types.NoOpToFrontend
